platform :ios, '10.3'

link_with 'EpocketCash', 'BlaBlaCash'
#target 'EpocketCash' do

    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'ART',
        'Core',
        'CxxBridge',
        'DevSupport',
        'RCTAnimation',
        'RCTGeolocation',
        'RCTImage',
        'RCTActionSheet',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
        'RCTCameraRoll'
    ]

    # React-Native dependencies
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

    # Firebase
    pod 'Firebase/Core', '~> 6.3.0'
    pod 'Firebase/Messaging', '~> 6.3.0'
    # pod 'Firebase/Performance', '~> 6.3.0'
    pod 'Fabric', '~> 1.10.2'
    pod 'Crashlytics', '~> 3.13.2'
    pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

    #Google maps
    pod 'react-native-maps', path: '../node_modules/react-native-maps'
    pod 'react-native-google-maps', path: '../node_modules/react-native-maps'
    pod 'GoogleMaps'
    pod 'Google-Maps-iOS-Utils'

    # React-Native libraries
    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
    pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'
    pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'
    pod 'react-native-camera', path: '../node_modules/react-native-camera'
    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
    pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
    pod 'RNFS', :path => '../node_modules/react-native-fs'
    pod 'RNSound', :path => '../node_modules/react-native-sound'
    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
    pod 'YandexMobileMetrica', '3.6.0'
    pod 'RNI18n', :path => '../node_modules/react-native-i18n'
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
    pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
    pod 'RNSVG', :path => '../node_modules/react-native-svg'
    pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'
    pod 'react-native-webview', :path => '../node_modules/react-native-webview'
    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
    pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'
    pod 'RNShare', :path => '../node_modules/react-native-share'
    pod 'react-native-video', :path => '../node_modules/react-native-video'
    pod 'react-native-image-editor', :path => '../node_modules/@react-native-community/image-editor'
    pod 'react-native-cookies', :path => '../node_modules/react-native-cookies/ios'
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'react-native-google-maps'
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
        if target.name == 'React'
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_ENABLE_INSPECTOR=0'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ENABLE_PACKAGER_CONNECTION=0'
            end
        end
        if target.name == 'RNFirebase' 
            target.build_configurations.each do |config|
                config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
            end
        end
    end
end
