platform :ios, '10.3'

target 'EpocketCash' do

    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge',
        'DevSupport',
        'RCTAnimation',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket',
    ]

    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

    pod 'react-native-maps', path: '../node_modules/react-native-maps'
    pod 'react-native-google-maps', path: '../node_modules/react-native-maps'
    pod 'GoogleMaps'
    pod 'Google-Maps-iOS-Utils'
    pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation'
    pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'
    pod 'react-native-camera', path: '../node_modules/react-native-camera'
    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
    pod 'Firebase/Core', '5.20.2'
    pod 'Firebase/Messaging', '5.20.2'
    pod 'Firebase/Performance', '5.20.2'
    pod 'Fabric', '1.9.0'
    pod 'Crashlytics', '3.12.0'
    pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
    pod 'FBSDKCoreKit', '~> 5.0.0'
    pod 'FBSDKLoginKit', '~> 5.0.0'
    pod 'FBSDKShareKit', '~> 5.0.0'
    pod 'RNInstagramStoryShare', :path => '../node_modules/react-native-instagram-story-share/ios'
    pod 'RNFS', :path => '../node_modules/react-native-fs'
    pod 'RNSound', :path => '../node_modules/react-native-sound'
    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
    pod 'jail-monkey', :path => '../node_modules/jail-monkey'
    pod 'YandexMobileMetrica', '3.6.0'
    pod 'RNI18n', :path => '../node_modules/react-native-i18n'
    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
    pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
    pod 'RNSVG', :path => '../node_modules/react-native-svg'
    pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'
    pod 'react-native-webview', :path => '../node_modules/react-native-webview'
    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
    pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'
    pod 'RNShare', :path => '../node_modules/react-native-share'
    pod 'lottie-ios', :path => '../node_modules/lottie-ios'
    pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
    pod 'react-native-video', :path => '../node_modules/react-native-video'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'react-native-google-maps'
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
        if target.name == "React"
            target.remove_from_project
        end
    end
end
