default_platform(:ios)

platform :ios do

    lane :development do
        ENV["FASTLANE_USER"] = "director@okoshko.ua"
        ENV["FASTLANE_PASSWORD"] = "Dom59K334"
        ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "tfzd-eoup-xpap-szbd"
        get_certificates
        get_provisioning_profile
        increment_build_number(
            build_number: latest_testflight_build_number + 1,
            xcodeproj: "EpocketCash.xcodeproj"
        )
        build_app(workspace: "EpocketCash.xcworkspace", scheme: "EpocketCash")
        upload_to_testflight(skip_waiting_for_build_processing: true)
    end

    lane :production do
        ENV["FASTLANE_USER"] = "director@okoshko.ua"
        ENV["FASTLANE_PASSWORD"] = "Dom59K334"
        ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "tfzd-eoup-xpap-szbd"
        get_certificates
        get_provisioning_profile
        increment_build_number(
            build_number: latest_testflight_build_number + 1,
            xcodeproj: "EpocketCash.xcodeproj"
        )
        build_app(workspace: "EpocketCash.xcworkspace", scheme: "EpocketCash")
        upload_to_testflight(skip_waiting_for_build_processing: true)
    end
    
end